### ISSUE TITLE
Can't run on Windows 10

### ISSUE THREAD

**Issue by hazarkarabay** [ribasco/glcd-emulator#8]
Hi, I installed `glcd-emulator-setup-amd64.exe` but unfortunately it can't launch.

* Clicking to `GLCD Simulator.exe` created by the installer gives 3 seperate error messages. First a blank box titled by "Failed to find library.", then `Failed to locate JNI_CreateJavaVM` and finally `Failed to launch JVM`.
* If I manually launch it via `java -jar app/glcd-emulator-1.1.0-alpha.jar` the main program window launches normally. But when I click the Fonts button, a Java exception pops up shown below. 

![image](https://user-images.githubusercontent.com/1272755/55746071-77c0aa00-5a41-11e9-83ea-5e217cc23961.png)

Java version (not sure if it is related but..)
```
C:\Users\Hazar>java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) Client VM (build 25.201-b09, mixed mode)
```

Am I doing something wrong?

Here is the full trace:
```
java.lang.ExceptionInInitializerError
	at com.ibasco.ucgdisplay.drivers.glcd.U8g2DriverAdapter.initialize(U8g2DriverAdapter.java:68)
	at com.ibasco.ucgdisplay.drivers.glcd.GlcdBaseDriver.initialize(GlcdBaseDriver.java:124)
	at com.ibasco.ucgdisplay.drivers.glcd.GlcdDriver.<init>(GlcdDriver.java:62)
	at com.ibasco.ucgdisplay.drivers.glcd.GlcdDriver.<init>(GlcdDriver.java:57)
	at com.ibasco.glcdemulator.DriverFactory.createVirtual(DriverFactory.java:119)
	at com.ibasco.glcdemulator.DriverFactory.createVirtual(DriverFactory.java:60)
	at com.ibasco.glcdemulator.utils.FontRenderer.initialize(FontRenderer.java:91)
	at com.ibasco.glcdemulator.utils.FontRenderer.<init>(FontRenderer.java:86)
	at com.ibasco.glcdemulator.utils.FontRenderer.<init>(FontRenderer.java:39)
	at com.ibasco.glcdemulator.utils.FontRenderer$InstanceHolder.<clinit>(FontRenderer.java:82)
	at com.ibasco.glcdemulator.utils.FontRenderer.getInstance(FontRenderer.java:129)
	at com.ibasco.glcdemulator.controllers.GlcdFontBrowserController.<init>(GlcdFontBrowserController.java:165)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at com.ibasco.glcdemulator.Controllers.lambda$getController$0(Controllers.java:91)
	at java.util.HashMap.computeIfAbsent(Unknown Source)
	at com.ibasco.glcdemulator.Controllers.getController(Controllers.java:80)
	at com.ibasco.glcdemulator.Controllers.getController(Controllers.java:53)
	at com.ibasco.glcdemulator.utils.ResourceUtil.lambda$loadFxmlResource$0(ResourceUtil.java:116)
	at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:929)
	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(FXMLLoader.java:971)
	at javafx.fxml.FXMLLoader$Element.processStartElement(FXMLLoader.java:220)
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:744)
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
	at com.ibasco.glcdemulator.utils.ResourceUtil.loadFxmlResource(ResourceUtil.java:119)
	at com.ibasco.glcdemulator.StageHelper.createStageFromResource(StageHelper.java:76)
	at com.ibasco.glcdemulator.StageHelper.createDialog(StageHelper.java:62)
	at com.ibasco.glcdemulator.StageHelper.createDialog(StageHelper.java:58)
	at com.ibasco.glcdemulator.Stages.getFontBrowserStage(Stages.java:85)
	at com.ibasco.glcdemulator.controllers.GlcdEmulatorController.openFontBrowserAction(GlcdEmulatorController.java:1814)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8411)
	at javafx.scene.control.Button.fire(Button.java:185)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.ibasco.ucgdisplay.common.exceptions.NativeLibraryLoaderException: Unable to load required native library
	at com.ibasco.ucgdisplay.core.u8g2.U8g2Graphics.<clinit>(U8g2Graphics.java:163)
	... 87 more
Caused by: java.io.IOException: Couldn't find resource lib/windows/x86/ ucgdisp.dll
	at org.scijava.nativelib.BaseJniExtractor.extractJni(BaseJniExtractor.java:158)
	at com.ibasco.ucgdisplay.common.utils.UCGDJniExtractor.findLibrary(UCGDJniExtractor.java:94)
	at com.ibasco.ucgdisplay.common.utils.UCGDJniExtractor.extractJni(UCGDJniExtractor.java:52)
	at org.scijava.nativelib.NativeLoader.loadLibrary(NativeLoader.java:126)
	at com.ibasco.ucgdisplay.common.utils.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:53)
	at com.ibasco.ucgdisplay.core.u8g2.U8g2Graphics.<clinit>(U8g2Graphics.java:161)
	... 87 more

```

**Comment by ribasco** [comment]
Thanks for providing the details, is your windows OS 32 bit?

**Comment by hazarkarabay** [comment]
It's 64 bit and thanks to your comment I found out that I have the 32 bit Java. After installing the 64bit version the issue goes away. You may want to include this detail in your README, apparently Java installer defaults to 32 bit installation even on 64 bit systems.

Thanks!

**Comment by ribasco** [comment]
Please do note that the application does not support 32 bit java (yet). Thanks for the feedback, I will update the readme.
